name: "Continuous Integration"

env:
  GH_OAUTH_TOKEN: ${{ secrets.GH_OAUTH_TOKEN }}

on:
  push:
    branches:
      - "develop"
      - "staging"
  pull_request:
    branches:
      - "develop"
      - "staging"

jobs:
  ci:
    runs-on: "ubuntu-18.04"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v2"

      - name: "Install Node.js 12.x"
        uses: "actions/setup-node@v1"
        with:
          node-version: "12.x"

      - uses: "actions/cache@v2"
        with:
          key: ${{ runner.os }}-modules-${{ hashFiles('./yarn.lock') }}
          path: "./node_modules"

      - name: "Install dependencies"
        run: "yarn install --immutable"

      - name: "Lint TypeScript code"
        run: "yarn run lint"

      - name: "Run unit tests"
        run: "yarn run test:unit"

      - name: "Run integration tests"
        run: "yarn run test:integration"
